name: test

on: 
  push:
    branches:
      - main
    paths:
      - ./platform/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prev
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Source
        uses: 'actions/checkout'

      - name: Configure Google Auth
        uses: 'google-github-actions/auth'
        with:
          token_format: access_token
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}